config/routes.rb
Rails.application.routes.draw do
  get 'called/payments'

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :products do 
   resources :comments
end 

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'
  get 'static_pages/contact'
  #root 'static_pages#index'
  get 'static_pages/index'
  root 'static_pages#landing_page'
  get 'static_pages/landing_page'
  post'static_pages/thank_you'
  post 'payments/create'
  mount ActionCable.server => '/cable'
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  validates :name, presence: true

  def self.search(search_term)
    if Rails.env.development?
      Product.where("name LIKE ?", "%#{search_term}%")
    else
      Product.where("name ilike ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
     if params[:q]
       search_term = params[:q]
       @products = Product.search(search_term)
     else
       @products = Product.all
    end

    @products = @products.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
 module ProductsHelper
   def cache_key_for_products
     count          = Product.count
     max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
     "products/all-#{count}-#{max_updated_at}"
   end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            <% if signed_in? && current_user.admin? %>
                <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>   
        </div>
    <% end %>
   <div class="flickr_pagination">
       <%= will_paginate @comments %>
    </div>

</div>

app/views/products/_form.html.erb
  <div class="field form-group pad-top">
  

  <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
          <div id="error_explanation">

          </div>
      <% end %>
  
    <div class="form-group field">
      <%= f.text_field :name, class: "form-control", placeholder: "name"  %>
      </div>

    <div class="form-group field">
       <%= f.text_area :description, class: "form-control", placeholder: "description"  %>
      </div>

     <div class="form-group field">
       <%= f.text_field :image_url, class: "form-control", placeholder: "image_url" %>
      </div>

    <div class="form-group form field">
       <%= f.text_field :colour, class: "form-control", placeholder: "color" %>
      </div>

     <div class="form-group form field">
       <%= f.text_field :price, class: "form-control", placeholder: "price" %>
      </div>

     <div class: "btn btn-primary btn-block">
      <%= f.submit "Create product", class: "btn btn-primary btn-block", type: "submit" %>
      </div>
  

 <% end %>

   

app/views/products/_new_comment.html.erb
<% if signed_in? %>
    <div class="text-center">
      <%= form_for([@product, @product.comments.build], class: "form-group", remote: true) do |f| %>
        <p>
          <%= f.label :body, "Review" %><br>
          <%= f.text_area :body, class: "form-control  col-md-12 col-sm-12 ", rows: 5 %>
        </p>
        <br>
        <br>
        <p>

         <div class="rating col-xs-12">
          </div>

        </p>  
        <p>
          <%= f.submit "Submit", class: "btn btn-primary " %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
 
 <div class="container">
  <div class="row">
   <% if signed_in? && current_user.admin? %>
   <h3><%= link_to 'Create new product', new_product_path, class: 'btn btn-default' %></h3>
   <% end %>
   <br>

   <% @products.each do |product| %>
   <% cache product do %>
   <div class="col-md-4 col-sm-6 col-xs-12">
   <h3><%= product.name %></h3>
    <% if product.image_url.present? %>
    <%= link_to(image_tag(product.image_url, class: "img-responsive product-image"), product) %>
    <% else %>
    "No image."
    <% end %>
    <p>
      <%= product.description %><br>
      <%= product.colour %><br>
      <%= product.price %>&euro;<br></p>

     <%= link_to 'Show', product, class:'btn btn-default'%>
        <% if signed_in? && current_user.admin? %>
           <%= link_to 'Edit', edit_product_path(product),class:'btn btn-default' %>
        <% end %>
        <% if signed_in? && current_user.admin? %>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-default'%>
        <% end %>
        </p>
      </div><!-- /col -->
    <% end %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<br>
<h1>Editing Product</h1>

<div class="container">

<%= render 'form', product: @product, class:'btn btn-default' %>
<br>

<%= link_to 'Show', @product, class: "btn btn-default" %> 
<%= link_to 'Back', products_path, class:'btn btn-default'  %>
    </div> 
</div>

app/views/products/index.html.erb
<div class="pad-top pad-bottom">
  <h1>Products</h1>
</div>

<table>
  <%#thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead%>
<% cache(cache_key_for_products) do %>
<%= render partial: 'product' %>
<% end %>
</table>
<div class="flickr_pagination">
       <%= will_paginate @products %>
    </div>

app/views/products/new.html.erb
  <div class="pad-top-double">
     <h1>New Product</h1>
   </div>
    <%= render 'form', product: @product %>
 

app/views/products/show.html.erb
<div class="container">
  <div class="show_product" data-product-id="<%= @product.id %>">
    <% cache @product do %>
    <br>
    <br>
    <div class="col-md-12">
    <br>
    <br>
      <h2>
        <%= @product.name %>
      </h2>
    </div>
     <div class="col-s-12">
      <p>
        <strong>
          <%= image_tag(@product.image_url, class: "img-zoom", data_zoom_image: "@product.image_url") %>
        </strong>
      </p>
    </div>
    <div class="col-md-12">
      <p>
        <%= @product.price / 1 %>
      </p>
      <div class="payment">
        <%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
      </div>

      <p>
        <%= @product.description %>
      </p>
      <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>">
      </div>
    </div>
    <% end %>
  </div>

  <div class="rate-product">
    <div class="col-md-6 rate-product">
      <h4>Customer reviews:</h4>
      <div class="alert alert-info-review" style="display:none" role="alert">A new comment was posted!</div>


      <p>
        <%= render partial: "comments" %>
      </p>
    </div>

    <div class="col-md-6 rate-product">
      <p>
        <%= render partial: "new_comment" %>
      </p>
           <br>
      <br>
        <% if signed_in? && current_user.admin? %>
  <div class="product-button col-md-12">
    <%= link_to 'Edit', edit_product_path(@product),class: 'btn btn-default' %>  
    <%= link_to 'Back', products_path, class: 'btn btn-default'  %>
  </div>
  <% end %>
  <br>

    </div>
  </div>

  
  <br>
  <br>

</div>