config/routes.rb
Rails.application.routes.draw do
  get 'called/payments'

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :products do 
   resources :comments
end 

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'
  get 'static_pages/contact'
  #root 'static_pages#index'
  get 'static_pages/index'
  root 'static_pages#landing_page'
  get 'static_pages/landing_page'
  post'static_pages/thank_you'
  post 'payments/create'
  mount ActionCable.server => '/cable'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traveller-Wonders</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
</head>

<body>
  <!-- navbar starts here -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- start navbar header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="projectName navbar-brand">TW'17</a>

    </div><!-- end navbar header -->
 
    <ul class="nav navbar-nav navbar-right">
      <li class="search-form field">
    <%= form_tag("/products", method: "get") do %>
     <!-- <%= label_tag(:q, "Search for:") %> -->
    <%= text_field_tag(:q, nil, :placeholder => 'Search for a product', class: 'search-field') %>
      <%= submit_tag("Search", class: 'search-button') %>
    <% end %>
            </li>
        <li>
          <%= link_to "HOME", static_pages_landing_page_path %>
        </li>
          <li>
          <%= link_to "PRODUCTS",products_path %>
          </li>
        <li>
          <%= link_to "ABOUT", static_pages_about_path %>
        </li>
        <li>
          <%= link_to 'CONTACT', static_pages_contact_path %>
        </li>
  <% if user_signed_in? %>
              <li>
                <%= link_to('LOGOUT', destroy_user_session_path, :method => :delete) %>
              </li>
             
            <% else %>
             <li>
               <%= link_to('LOGIN/SIGN UP', new_user_session_path) %>
             </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<% if notice %>
        <p id="notice" class="notice alert alert-info"><%= notice %></p>
        <% end %>

        <% if alert %>
        <p id="alert" class="alert alert-info"><%= alert %></p>
        <% end %>
<%= yield %>

<!-- footer -->
 <!-- footer nav -->
 

 <footer>
      &copy; 2017 Traveller Wonders
  </footer>


</body>
</html>